### ISSUE TITLE
0.1 Milestones (due Friday)

### ISSUE THREAD

**Issue by jmulford-bandwidth** [Bandwidth/messaging-java-sdk#5]
All tasks should have proper documentation (in the Readme would be great)

Docs for these end points can be found here: https://dev.bandwidth.com/v2-messaging/methods/sendMessages.html

- [ ] Send message, receive response
- [ ] Send group message, receive response
- [ ] Receive callbacks from Bandwidth (incoming messages)

**Comment by fuchsnj** [comment]
replaced with individual issues
